Rename swap functions which conflict on OpenBSD
OpenBSD provides swap macros with the same names swap16/swap32

utils/listmem.cpp:31:38: error: too many arguments provided to function-like macro invocation
static void swap16(unsigned char *d, const unsigned char *s, int n)
                                     ^
/usr/include/sys/endian.h:70:9: note: macro 'swap16' defined here